controllers:
  - name: "MTMR-franka"
    loader:
      lib_name: medrct_default_controller
      class_name: DefaultControllerFactory
      create_class_name: "CartesianFollowerController"
    input:
      topic: "/quest_controller_pose/right/pose"
      position_scale: 0.3
      # hold_home_off:
      #   servo_cp_topic: /MTMR/servo_cp
      #   servo_cf_topic: /MTMR/body/servo_cf
    harmonize_joint_position_outputs: False
    output:
      control_topic: "/medrct_franka/servo_jp"
      feedback_topic: "/medrct_franka/measured_js"
    kinematics:
      forward:
        lib_name: "medrct_franka_env"
        class_name: "FrankaForwardKinematicsFactory"
        config:
      inverse:
        lib_name: "medrct_franka_env"
        class_name: "FrankaInverseKinematicsFactory"
        config:
control_groups:
  - name: default
    controller_names: ["MTMR-franka"]
active_control_group: "default"
basic_communicator:
  auto_enable: False
  enable_topic: "/quest_controller_pose/enabled"
  clutch_topic: "/quest_controller_pose/clutch"
