controllers:
  - name: "Keyboard-PSM2"
    loader:
      lib_name: medrct_default_controller
      class_name: DefaultControllerFactory
      create_class_name: "CartesianIncrementController"
    input:
      topic: "/keyboard/twist"
    output:
      control_topic: "/medrct_franka/servo_jp"
      feedback_topic: "/medrct_franka/measured_js"
    kinematics:
      forward:
        lib_name: "medrct_franka_env"
        class_name: "FrankaForwardKinematicsFactory"
        config:
      inverse:
        lib_name: "medrct_franka_env"
        class_name: "FrankaInverseKinematicsFactory"
        config:
basic_communicator:
  auto_enable: True
