controllers:
  - name: "RL-PSM1"
    loader:
      lib_name: medrct_default_controller
      class_name: DefaultControllerFactory
      create_class_name: "CartesianIncrementController"
    input:
      topic: "/PSM1/increment"
      data_type: "Pose"
      topic_type: "PoseStamped"
    output:
      control_topic: "/PSM1/servo_jp"
      feedback_topic: "/PSM1/measured_js"
    kinematics:
      forward:
        lib_name: "medrct_dvrk_env"
        class_name: "PsmForwardKinematicsFactory"
        config:
          tool_name: "LND400006"
      inverse:
        lib_name: "medrct_dvrk_env"
        class_name: "PsmInverseKinematicsFactory"
        config:
          tool_name: "LND400006"
basic_communicator:
  auto_enable: True
