cartesian_controllers:
  - name: "MTMR-PSM2"
    input:
      position_scale: 0.5
      type: "follow"
      topic: "/MTMR/measured_cp"
      topic_type: "PoseStamped"
      hz_divisor: 4
      is_input_device_hold_home_off: True
      servo_cp_topic: "/MTMR/servo_cp"
      servo_cf_topic: "/MTMR/body/servo_cf"
    output:
      control_interfaces:
        - control_topic: "/PSM2/servo_jp"
          feedback_topic: "/PSM2/measured_js"
    kinematics:
      robot: "psm"
      tool:
        type: "LND400006"
joint_controllers:
  - name: "MTMR-PSM2Jaw"
    input:
      type: "follow"
      topic: "/MTMR/gripper/measured_js"
    output:
      control_interfaces:
        - control_topic: "/PSM2/jaw/servo_jp"
          feedback_topic: "/PSM2/jaw/measured_js"
clutch_topic: "/console/clutch"
switcher:
  switch_topic: "/console/operator_present"
  disable_list: []
  enable_list: ["MTMR-PSM2", MTMR-PSM2Jaw]
enable_at_start: []
