controllers:
  - name: "Keyboard-PSM1"
    loader:
      lib_name: medrct_default_controller
      class_name: DefaultControllerFactory
      create_class_name: "CartesianIncrementController"
    input:
      topic: "/keyboard/twist"
    output:
      control_topic: "/PSM1/servo_jp"
      feedback_topic: "/PSM1/measured_js"
    kinematics:
      forward:
        lib_name: "medrct_dvrk_env"
        class_name: "PsmForwardKinematicsFactory"
        config:
          tool_name: "LND400006"
          scale: 20
      inverse:
        lib_name: "medrct_dvrk_env"
        class_name: "PsmInverseKinematicsFactory"
        config:
          tool_name: "LND400006"
          scale: 20
  - name: "Keyboard-PSM1-Jaw"
    loader:
      lib_name: medrct_default_controller
      class_name: DefaultControllerFactory
      create_class_name: "JointIncrementController"
    input:
      topic: "/keyboard/joint_state"
    output:
      control_topic: "/PSM1/jaw/servo_jp"
      feedback_topic: "/PSM1/jaw/measured_js"
basic_communicator:
  auto_enable: True
