cartesian_controllers:
  - name: "Keyboard-PSM1"
    input:
      type: "increment"
      topic: "/keyboard/twist"
    output:
      control_topic: "/PSM1/servo_jp"
      feedback_topic: "/PSM1/measured_js"
    kinematics:
      robot: "psm"
      tool: "LND40006"
  - name: "MTML-PSM2"
    input:
      type: "follow"
      topic: "/MTML/measured_cp"
    output:
      control_topic: "/PSM2/servo_jp"
      feedback_topic: "/PSM2/measured_js"
      base_to_camera_rot:
        quaternion:
          x: 0
          y: 0
          z: 1
          w: 0
    kinematics:
      robot: "psm"
      tool: "LND40006"
joint_controllers:
  - name: "Keyboard-PSM1Jaw"
    input:
      type: "increment"
      topic: "/keyboard/joint_state"
      scale: "1.2"
    output:
      control_topic: "/PSM1/jaw/servo_jp"
      feedback_topic: "/PSM1/jaw/measured_js"

enable_at_start: ["Keyboard-PSM1", Keyboard-PSM1Jaw]
clutch_topic: "/console/clutch"
switcher:
  switch_topic: "/console/camera"
  disable_list: ["Keyboard-PSM1", Keyboard-PSM1Jaw]
  enable_list: ["MTML-PSM2"]
