cartesian_controllers:
  - name: "MTMR-PSM1"
    input:
      type: "follow"
      topic: "/MTMR/measured_cp"
    output:
      control_topic: "/PSM1/servo_jp"
      feedback_topic: "/PSM1/measured_js"
    kinematics:
      robot: "psm"
      tool:
        type: "LND40006"
joint_controllers:
  - name: "MTMR-PSM1Jaw"
    input:
      type: "follow"
      topic: "/MTMR/gripper/measured_js"
    output:
      control_topic: "/PSM1/jaw/servo_jp"
      feedback_topic: "/PSM1/jaw/measured_js"
