controllers:
  - name: "Keyboard-PSM1"
    input:
      type: "increment"
      topic: "/keyboard/twist"
    output:
      control_topic: "/PSM1/servo_jp"
      feedback_topic: "/PSM1/measured_js"
    kinematics:
      robot: "psm"
      tool: "LND40006"
